### ISSUE TITLE
Requests an Owner when the Machine may not Have One

### ISSUE THREAD

**Issue by pod10** [lilwayne1556/IT-Client-Services#1]
One of the first things the script requests during run is the name of a machine's owner, to fill out in the database.
This is not ideal with machines that are shared, as they do not necessarily have an associated catID to look up and grab info from.

For the time being, the workaround is to use the supervisor that "oversees" that particular department as the owner, eg Cheryl Moses for FM, Sam Barr for EM or SA, etc.

We'll need to find a way to handle cases like, assuming this workaround is not ideal. If necessary, being able to scrub the computer name for the name scheme (catID vs room number) to differentiate would be a decent functionality addition.
I attached a spreadsheet with all the buildings I can think of that we support "typical" (checklisted) machines inside of, to use for checking machine names, if needed.
[Building abbr list.xlsx](https://github.com/lilwayne1556/IT-Client-Services/files/2434839/Building.abbr.list.xlsx)

**Comment by lilwayne1556** [comment]
I talked to Michael and we will be using the department that the computer is in
